**Dataset Preparation**

In [1]:
import pandas as pd # pandas is used to read files of the datasets
from sklearn.model_selection import train_test_split # train_test_split is used to part
from sklearn.naive_bayes import GaussianNB # GaussianNB() is the naive bayes classifier
from sklearn.svm import SVC # SVC() is the Support Vector Machines Classifier
from sklearn.neural_network import MLPClassifier # MLPClassifier us the Neural Network
from sklearn.metrics import confusion_matrix, classification_report # Confusion_matrix

In [ ]:
df=pd.read_csv('heart.csv') # Read the dataset in a new data frame(df)
df.head() # Display the first five rows (5 premières lignes)

Age Sex ChestPainType  ...  Oldpeak  ST_Slope  HeartDisease
0   40   M           ATA  ...      0.0        Up             0
1   49   F           NAP  ...      1.0      Flat             1
2   37   M           ATA  ...      0.0        Up             0
3   48   F           ASY  ...      1.5      Flat             1
4   54   M           NAP  ...      0.0        Up             0

[5 rows x 12 columns]

In [ ]:
df.tail() # Display the last five rows (5 denières lignes)

Age Sex ChestPainType  ...  Oldpeak  ST_Slope  HeartDisease
913   45   M            TA  ...      1.2      Flat             1
914   68   M           ASY  ...      3.4      Flat             1
915   57   M           ASY  ...      1.2      Flat             1
916   57   F           ATA  ...      0.0      Flat             1
917   38   M           NAP  ...      0.0        Up             0

[5 rows x 12 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


**LabelEncoder**

In [ ]:
from sklearn.preprocessing import LabelEncoder
X = LabelEncoder() # created a instance of label encoder
df.Sex = X.fit_transform(df.Sex)
df.ChestPainType = X.fit_transform(df.ChestPainType)
df.RestingECG = X.fit_transform(df.RestingECG)
df.ExerciseAngina = X.fit_transform(df.ExerciseAngina)
df.ST_Slope = X.fit_transform(df.ST_Slope)

df.head(10)

Age  Sex  ChestPainType  ...  Oldpeak  ST_Slope  HeartDisease
0   40    1              1  ...      0.0         2             0
1   49    0              2  ...      1.0         1             1
2   37    1              1  ...      0.0         2             0
3   48    0              0  ...      1.5         1             1
4   54    1              2  ...      0.0         2             0
5   39    1              2  ...      0.0         2             0
6   45    0              1  ...      0.0         2             0
7   54    1              1  ...      0.0         2             0
8   37    1              0  ...      1.5         1             1
9   48    0              1  ...      0.0         2             0

[10 rows x 12 columns]

In [ ]:
# example of a normalization
from numpy import asarray
from sklearn.preprocessing import MinMaxScaler
# define data

print(df)
# define min max scaler
scaler = MinMaxScaler()
# transform data
scaled = scaler.fit_transform(df)
print(scaled)


     Age  Sex  ChestPainType  ...  Oldpeak  ST_Slope  HeartDisease
0     40    1              1  ...      0.0         2             0
1     49    0              2  ...      1.0         1             1
2     37    1              1  ...      0.0         2             0
3     48    0              0  ...      1.5         1             1
4     54    1              2  ...      0.0         2             0
..   ...  ...            ...  ...      ...       ...           ...
913   45    1              3  ...      1.2         1             1
914   68    1              0  ...      3.4         1             1
915   57    1              0  ...      1.2         1             1
916   57    0              1  ...      0.0         1             1
917   38    1              2  ...      0.0         2             0

[918 rows x 12 columns]
[[0.24489796 1.         0.33333333 ... 0.29545455 1.         0.        ]
 [0.42857143 0.         0.66666667 ... 0.40909091 0.5        1.        ]
 [0.18367347 1.         0

In [ ]:
X=df.drop('HeartDisease',axis=1) 
y=df['HeartDisease']
X.head()

Age  Sex  ChestPainType  RestingBP  ...  MaxHR  ExerciseAngina  Oldpeak  ST_Slope
0   40    1              1        140  ...    172               0      0.0         2
1   49    0              2        160  ...    156               0      1.0         1
2   37    1              1        130  ...     98               0      0.0         2
3   48    0              0        138  ...    108               1      1.5         1
4   54    1              2        150  ...    122               0      0.0         2

[5 rows x 11 columns]

In [ ]:
# example of a normalization
from numpy import asarray
from sklearn.preprocessing import MinMaxScaler
# define data

# define min max scaler
scaler = MinMaxScaler()
# transform data
scaled = scaler.fit_transform(X)



In [ ]:
df.corr()

Age       Sex  ...  ST_Slope  HeartDisease
Age             1.000000  0.055750  ... -0.268264      0.282039
Sex             0.055750  1.000000  ... -0.150693      0.305445
ChestPainType  -0.077150 -0.126559  ...  0.213521     -0.386828
RestingBP       0.254399  0.005133  ... -0.075162      0.107589
Cholesterol    -0.095282 -0.200092  ...  0.111471     -0.232741
FastingBS       0.198039  0.120076  ... -0.175774      0.267291
RestingECG     -0.007484  0.071552  ... -0.006778      0.057384
MaxHR          -0.382045 -0.189186  ...  0.343419     -0.400421
ExerciseAngina  0.215793  0.190664  ... -0.428706      0.494282
Oldpeak         0.258612  0.105734  ... -0.501921      0.403951
ST_Slope       -0.268264 -0.150693  ...  1.000000     -0.558771
HeartDisease    0.282039  0.305445  ... -0.558771      1.000000

[12 rows x 12 columns]

**Partitioning DataPartitioning Data**

In [ ]:
[X_train,X_test,y_train,y_test]=train_test_split(X,y,test_size=0.2)
print("Train dataset size: {}/{}".format(len(X_train),len(y)))
print("Test dataset size: {}/{}".format(len(X_test),len(y)))

Train dataset size: 734/918
Test dataset size: 184/918


**Machine Learning: NB Vs SVM Vs Neural Network**

In [ ]:
gnb=GaussianNB() # gnb is a naive bayes classifier
linear_svm =SVC(kernel='linear') # linear_svm is a Linear Support Vectors
rbf_svm =SVC(kernel='rbf') # rbf_svm is a RBF support vectors
sigmoid_svm =SVC(kernel='sigmoid')# sigmoid support vectors
ploy_svm =SVC(kernel='poly',degree=2) # Ploynom with degree=2 as support vectors
neural=MLPClassifier(hidden_layer_sizes=(100,20),activation='relu',solver='adam')

In [ ]:
gnb.fit(X_train,y_train) # Train Guassian NB classifier
linear_svm.fit(X_train,y_train) # Train SVM
rbf_svm.fit(X_train,y_train)
sigmoid_svm.fit(X_train,y_train)
ploy_svm.fit(X_train,y_train)
neural.fit(X_train,y_train) # Train Neural Network - finding the best weight matrix

MLPClassifier(hidden_layer_sizes=(100, 20))

In [ ]:
y_nb=gnb.predict(X_test)
y_linear_svm=linear_svm.predict(X_test)
y_rbf_svm=rbf_svm.predict(X_test)
y_ploy_svm=ploy_svm.predict(X_test)
y_sigmoid_svm=sigmoid_svm.predict(X_test)
y_neural=neural.predict(X_test)

**Performance Evaluation**

In [ ]:
print ('************* Peformance Evauation of Naive Bayes **************')
print(confusion_matrix(y_test,y_nb))
print(classification_report(y_test,y_nb))
print ('************* Peformance Evauation of Linear SVM **************')
print(confusion_matrix(y_test,y_linear_svm))
print(classification_report(y_test,y_linear_svm))
print ('************* Peformance Evauation of RBF SVM **************')
print(confusion_matrix(y_test,y_rbf_svm))
print(classification_report(y_test,y_rbf_svm))
print ('************* Peformance Evauation of Sigmoid SVM **************')
print(confusion_matrix(y_test,y_sigmoid_svm))
print(classification_report(y_test,y_sigmoid_svm))
print ('************* Peformance Evauation of Polynomial (2) SVM **************')
print(confusion_matrix(y_test,y_ploy_svm))
print(classification_report(y_test,y_ploy_svm))
print ('************* Peformance Evauation of Neural Network **************')
print(confusion_matrix(y_test,y_neural))
print(classification_report(y_test,y_neural))

************* Peformance Evauation of Naive Bayes **************
[[69 15]
 [14 86]]
              precision    recall  f1-score   support

           0       0.83      0.82      0.83        84
           1       0.85      0.86      0.86       100

    accuracy                           0.84       184
   macro avg       0.84      0.84      0.84       184
weighted avg       0.84      0.84      0.84       184

************* Peformance Evauation of Linear SVM **************
[[68 16]
 [14 86]]
              precision    recall  f1-score   support

           0       0.83      0.81      0.82        84
           1       0.84      0.86      0.85       100

    accuracy                           0.84       184
   macro avg       0.84      0.83      0.84       184
weighted avg       0.84      0.84      0.84       184

************* Peformance Evauation of RBF SVM **************
[[56 28]
 [32 68]]
              precision    recall  f1-score   support

           0       0.64      0.67      0.65 

In [ ]:
import pickle
with open('model.pickle', 'wb') as handle:
    pickle.dump(gnb, handle)

In [ ]:
with open('/content/model.pickle', 'rb') as handle:
    b = pickle.load(handle)

In [ ]:
b.predict(X_test)

array([0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1])